/*
  Warnings:

  - You are about to drop the `Item` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Item";

-- CreateTable
CREATE TABLE "items" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "year" INT4 NOT NULL,
    "category" STRING NOT NULL,
    "ranking" STRING NOT NULL,
    "thumbnail" JSONB NOT NULL,
    "isTrending" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "items_pkey" PRIMARY KEY ("id")
);
