-- CreateTable
CREATE TABLE "Item" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "year" INT4 NOT NULL,
    "category" STRING NOT NULL,
    "ranking" STRING NOT NULL,
    "thumbnail" JSONB NOT NULL,
    "isTrending" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "Item_pkey" PRIMARY KEY ("id")
);
