version: '3.7'

x-environment: &-environment
  COCKROACH_DATABASE: environment
  COCKROACH_USER: cockroach
  COCKROACH_PASSWORD: cockroach

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18
    environment:
      <<: *-environment
    volumes:
      - ..:/workspace:cached
    network_mode: service:cockroachdb
    command: sleep infinity

  cockroachdb:
    image: cockroachdb/cockroach:latest
    environment:
      <<: *-environment
    command: start-single-node

    volumes:
      - db:/cockroach/cockroach-data

volumes:
  db:
