/*
  Warnings:

  - You are about to alter the column `id` on the `items` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_items" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "year" INT4 NOT NULL,
    "category" STRING NOT NULL,
    "rating" STRING NOT NULL,
    "thumbnail" JSONB NOT NULL,
    "is_trending" BOOL NOT NULL DEFAULT false,

    CONSTRAINT "items_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_items" ("category","id","is_trending","rating","thumbnail","title","year") SELECT "category","id","is_trending","rating","thumbnail","title","year" FROM "items";
DROP TABLE "items" CASCADE;
ALTER TABLE "_prisma_new_items" RENAME TO "items";
